# Generated by Django 3.2.4 on 2021-06-18 13:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('emotion_type', models.CharField(blank=True, max_length=16, null=True)),
                ('song_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KakaoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=100)),
                ('kakao_conversation', models.FileField(upload_to=blog.models.up_to)),
            ],
        ),
    ]
